name: build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: 'Build'
        run: ./gradlew build --no-daemon

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: MobArena.jar
          path: build/libs/MobArena-*.jar

      - name: 'Output version'
        id: version
        run: |
          version=$(
            unzip -p build/libs/MobArena-*.jar plugin.yml \
            | grep '^version: ' \
            | awk '{printf $2}' \
            | tr -d "'" \
          )
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
